apiVersion: v1
kind: Template
metadata:
  name: ace
  description: Template for deploy IBM App Connect Enteprise
  tags: ibmcom/ace
labels:
  template: ace
  version: "1.0"
  app: "${APPLICATION_NAME}"
parameters:
- description: ACE application name 
  required: true
  name: APPLICATION_NAME
- description: Image Name
  required: true
  name: IMAGE_NAME
- description: DB Password
  name: DB_PASSWORD
  required: true
- description: DB user
  name: DB_USER
  required: true
- description: DB password
  name: DB_PASSWORD
  required: true

objects:
- kind: Secret 
  apiVersion: v1
  metadata:
    name: ${APPLICATION_NAME}-db-secret
  spec: 
    stringData:
      setdbparms.txt: |-
        dbidentity ${DB_USER} ${DB_PASSWORD}
- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: ${APPLICATION_NAME}-policies
  spec:
    DB2Policy.policyxml: |-
      <?xml version="1.0" encoding="UTF-8"?>
      <policies>
        <policy policyType="JDBCProviders" policyName="DB2Policy" policyTemplate="DB2_91_Windows">
          <databaseName>${DB_NAME}</databaseName>
          <databaseType>DB2 Universal Database</databaseType>
          <databaseVersion>10.6</databaseVersion>
          <type4DriverClassName>com.ibm.db2.jcc.DB2Driver</type4DriverClassName>
          <type4DatasourceClassName>com.ibm.db2.jcc.DB2XADataSource</type4DatasourceClassName>
          <connectionUrlFormat>jdbc:db2://[serverName]:[portNumber]/[databaseName]:user=[user];password=[password];</connectionUrlFormat>
          <connectionUrlFormatAttr1></connectionUrlFormatAttr1>
          <connectionUrlFormatAttr2></connectionUrlFormatAttr2>
          <connectionUrlFormatAttr3></connectionUrlFormatAttr3>
          <connectionUrlFormatAttr4></connectionUrlFormatAttr4>
          <connectionUrlFormatAttr5></connectionUrlFormatAttr5>
          <serverName>${DB_SERVICE_NAME}</serverName>
          <portNumber>${DB_PORT}</portNumber>
          <jarsURL>/home/aceuser/db2jcc-db2jcc4.jar</jarsURL>
          <databaseSchemaNames>${DB_SCHEMA}</databaseSchemaNames>
          <description></description>
          <maxConnectionPoolSize>0</maxConnectionPoolSize>
          <securityIdentity>dbidentity</securityIdentity>
          <environmentParms></environmentParms>
          <jdbcProviderXASupport>false</jdbcProviderXASupport>
          <useDeployedJars>false</useDeployedJars>
        </policy>
      </policies>
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: "${APPLICATION_NAME}"
  spec:
    replicas: 1
    selector: 
      template: ace
      version: "1.0"
      app: "${APPLICATION_NAME}"
    template:
      metadata:
        labels: 
          template: ace
          version: "1.0"
          app: "${APPLICATION_NAME}"
      spec:
        containers:
        - name: ace
          env: 
          - name: LICENSE
            value: accept
          image: " "
          imagePullPolicy: "Always"
          ports:
          - containerPort: 7600
            protocol: TCP
          - containerPort: 7800
            protocol: TCP
          - containerPort: 7843
            protocol: TCP
          - containerPort: 9483
            protocol: TCP
          livenessProbe: 
            exec:
              command: 
              - chkacehealthy
          readinessProbe: 
            exec:
              command: 
              - chkaceready
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1000
            privileged: false
            capabilities:
              add:
              - SETPCAP
              - AUDIT_WRITE
              - CHOWN
              - NET_RAW
              - DAC_OVERRIDE
              - FOWNER
              - FSETID
              - KILL
              - SETUID
              - SETGID
              - NET_BIND_SERVICE
              - SYS_CHROOT
              - SETFCAP
    triggers: 
    - type: ImageChange
      imageChangeParams:
        containerNames:
        - ace
        automatic: true
        from: 
          kind: ImageStreamTag
          name: "${IMAGE_NAME}"
    - type: ConfigChange
- kind: Service
  apiVersion: v1
  metadata:
    name: ${APPLICATION_NAME}
  spec:
    selector: 
      template: ace
      version: "1.0"
      app: "${APPLICATION_NAME}"
    type: ClusterIP
    ports:
    - name: 7600-tcp
      port: 7600
      protocol: TCP
      targetPort: 7600
    - name: 7800-tcp
      port: 7800
      protocol: TCP
      targetPort: 7800
    - name: 7843-tcp
      port: 7843
      protocol: TCP
      targetPort: 7843
    - name: 9843-tcp
      port: 9843
      protocol: TCP
      targetPort: 9843
- kind: Route
  apiVersion: v1
  metadata: 
    name: ${APPLICATION_NAME}
  spec: 
    port:
      targetPort: 7800-tcp
    to:
      kind: Service
      name: "${APPLICATION_NAME}"